### ISSUE TITLE
"This extension integrates seamlessly with Dnote CLI"?

### ISSUE THREAD

**Issue by xuchunyang** [dnote-io/browser-extension#11]
This browser extension has nothing to do with the command line client, right?

**Comment by sungwoncho** [comment]
What users write on the browser extension can be seamlessly synced to the users' computers using CLI. If the claim was confusing to you, I am open to suggestions on alternative wording.

**Comment by xuchunyang** [comment]
It was confusing when I first read it, this browser addon doesn't need to (maybe can't) call the cli tools to work.

I don't have any better idea, so closing.
