### ISSUE TITLE
Chrome Browser extension not opening correctly

### ISSUE THREAD

**Issue by bdonkey** [dnote-io/browser-extension#3]
Please see the attached images that show what occurs when I try dNote from Chrome:

* Chrome Version
<img width="679" alt="screen shot 2018-09-20 at 2 49 05 pm" src="https://user-images.githubusercontent.com/3912582/45843209-939e7180-bce4-11e8-95a1-1770af58b895.png">

* ctrD or Click on dNote:
<img width="103" alt="screen shot 2018-09-20 at 2 43 55 pm" src="https://user-images.githubusercontent.com/3912582/45843228-a153f700-bce4-11e8-8127-229be3c25ee5.png">

* click on black square at shown above:
<img width="362" alt="screen shot 2018-09-20 at 2 44 02 pm" src="https://user-images.githubusercontent.com/3912582/45843227-a153f700-bce4-11e8-99ac-4813c7a6e1d3.png">

* **Note** When clicking on the extension there is a white flash as if editing window attempts to show, but quickly dissapears and black square takes it place

* DNote extension version:
<img width="682" alt="screen shot 2018-09-20 at 2 57 06 pm" src="https://user-images.githubusercontent.com/3912582/45843540-85048a00-bce5-11e8-8491-33be5e7fd9ce.png">

**Comment by sungwoncho** [comment]
Could you check if this happens with the latest 0.2.0 release? https://chrome.google.com/webstore/detail/dnote/mcfbfmihbijfaambfbbfcdcfibcjcahi

**Comment by bdonkey** [comment]
Seems to work. Thank you! scott
